; generated by ARM C/C++ Compiler, 5.03 [Build 76]
; commandline ArmCC [--debug -c --asm -o.\debug\aducm360_test_lib.o --depend=.\debug\aducm360_test_lib.d --cpu=Cortex-M3 --apcs=interwork -O0 --omf_browse=.\debug\aducm360_test_lib.crf ADuCM360_Test_Lib.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

I2C_menu_display PROC
        PUSH     {r4,lr}
        LDR      r0,|L1.1000|
        BL       printf
        LDR      r0,|L1.1000|
        ADDS     r0,r0,#0x54
        BL       printf
        LDR      r0,|L1.1000|
        ADDS     r0,r0,#0xa8
        BL       printf
        LDR      r0,|L1.1000|
        ADDS     r0,r0,#0xfc
        BL       printf
        LDR      r0,|L1.1000|
        ADDS     r0,r0,#0x54
        BL       printf
        LDR      r0,|L1.1004|
        BL       printf
        LDR      r0,|L1.1000|
        ADDS     r0,r0,#0x54
        BL       printf
        LDR      r0,|L1.1000|
        BL       printf
        ADR      r0,|L1.1008|
        BL       printf
        POP      {r4,pc}
        ENDP

I2cMRdCfg PROC
        PUSH     {r4,lr}
        MOV      r3,r0
        SUBS     r0,r1,#1
        LDR      r4,|L1.1052|
        LDR      r4,[r4,#0]  ; pI2CMRXCNT
        STRH     r0,[r4,#0]
        LDR      r0,|L1.1052|
        LDR      r0,[r0,#0]  ; pI2CMRXCNT
        LDRH     r0,[r0,#0]
        ORRS     r0,r0,r2
        LDR      r4,|L1.1052|
        LDR      r4,[r4,#0]  ; pI2CMRXCNT
        STRH     r0,[r4,#0]
        CMP      r3,#0xff
        BLS      |L1.122|
        LDR      r4,|L1.1056|
        LDR      r4,[r4,#0]  ; pI2CADR1
        STRB     r3,[r4,#0]
        MOVS     r0,#6
        AND      r0,r0,r3,LSR #7
        ORR      r0,r0,#0xf0
        LDR      r4,|L1.1060|
        LDR      r4,[r4,#0]  ; pI2CADR0
        STRB     r0,[r4,#0]
        B        |L1.136|
|L1.122|
        LDR      r4,|L1.1060|
        LDR      r4,[r4,#0]  ; pI2CADR0
        STRB     r3,[r4,#0]
        MOVS     r0,#0
        LDR      r4,|L1.1056|
        LDR      r4,[r4,#0]  ; pI2CADR1
        STRB     r0,[r4,#0]
|L1.136|
        LDR      r0,|L1.1060|
        LDR      r0,[r0,#0]  ; pI2CADR0
        LDRB     r0,[r0,#0]
        ORR      r0,r0,#1
        LDR      r4,|L1.1060|
        LDR      r4,[r4,#0]  ; pI2CADR0
        STRB     r0,[r4,#0]
        MOVS     r0,#1
        POP      {r4,pc}
        ENDP

I2cMWrCfg PROC
        MOV      r1,r0
        MOV      r0,#0xfffe
        ANDS     r1,r1,r0
        CMP      r1,#0xff
        BLS      |L1.192|
        LDR      r2,|L1.1056|
        LDR      r2,[r2,#0]  ; pI2CADR1
        STRB     r1,[r2,#0]
        MOVS     r0,#6
        AND      r0,r0,r1,LSR #7
        ORR      r0,r0,#0xf0
        LDR      r2,|L1.1060|
        LDR      r2,[r2,#0]  ; pI2CADR0
        STRB     r0,[r2,#0]
        B        |L1.206|
|L1.192|
        LDR      r2,|L1.1060|
        LDR      r2,[r2,#0]  ; pI2CADR0
        STRB     r1,[r2,#0]
        MOVS     r0,#0
        LDR      r2,|L1.1056|
        LDR      r2,[r2,#0]  ; pI2CADR1
        STRB     r0,[r2,#0]
|L1.206|
        MOVS     r0,#1
        BX       lr
        ENDP

I2C_Read_ADE7953 PROC
        PUSH     {r4,lr}
        MOVS     r4,#0
        LDR      r0,|L1.1064|
        LDRB     r0,[r0,#0]  ; ucMasterRxDevAddr
        CMP      r0,#4
        BLT      |L1.230|
        LDR      r0,|L1.1064|
        LDRB     r0,[r0,#0]  ; ucMasterRxDevAddr
        CMP      r0,#6
        BLE      |L1.238|
|L1.230|
        LDR      r0,|L1.1064|
        LDRB     r0,[r0,#0]  ; ucMasterRxDevAddr
        CMP      r0,#9
        BLT      |L1.246|
|L1.238|
        ADR      r0,|L1.1068|
        BL       printf
        B        |L1.378|
|L1.246|
        MOVS     r0,#1
        LDR      r1,|L1.1124|
        STR      r0,[r1,#0]  ; ReadFlag
        MOVS     r0,#0
        LDR      r1,|L1.1128|
        STR      r0,[r1,#0]  ; uiMasterTxIndex
        MOV      r0,r1
        LDR      r1,[r0,#0]  ; uiMasterTxIndex
        LDR      r0,[r0,#0]  ; uiMasterTxIndex
        ADDS     r0,r0,#1
        LDR      r2,|L1.1128|
        STR      r0,[r2,#0]  ; uiMasterTxIndex
        LDR      r0,|L1.1064|
        LDRB     r0,[r0,r1]
        LDR      r1,|L1.1132|
        LDR      r1,[r1,#0]  ; pI2CMTX
        STRB     r0,[r1,#0]
        MOVS     r0,#0x70
        BL       I2cMWrCfg
        NOP      
|L1.288|
        LDR      r0,|L1.1136|
        LDRB     r0,[r0,#0]  ; ucComplete
        CMP      r0,#0
        BEQ      |L1.288|
        MOVS     r0,#0
        LDR      r1,|L1.1136|
        STRB     r0,[r1,#0]
        LDR      r0,|L1.1064|
        LDRB     r0,[r0,#0]  ; ucMasterRxDevAddr
        CMP      r0,#9
        BCS      |L1.364|
        TBB      [pc,r0]
        DCB      0x05,0x0d
        DCB      0x13,0x19,0x19,0x19
        DCB      0x19,0x06,0x07,0x00
        NOP      
        NOP      
        MOVS     r2,#0
        MOVS     r1,#1
        MOVS     r0,#0x70
        BL       I2cMRdCfg
        B        |L1.376|
        MOVS     r2,#0
        MOVS     r1,#2
        MOVS     r0,#0x70
        BL       I2cMRdCfg
        B        |L1.376|
        MOVS     r2,#0
        MOVS     r1,#3
        MOVS     r0,#0x70
        BL       I2cMRdCfg
        B        |L1.376|
|L1.364|
        MOVS     r2,#0
        MOVS     r1,#4
        MOVS     r0,#0x70
        BL       I2cMRdCfg
        NOP      
|L1.376|
        NOP      
|L1.378|
        MOVS     r4,#0
        B        |L1.390|
|L1.382|
        ADR      r0,|L1.1140|
        BL       printf
        ADDS     r4,r4,#1
|L1.390|
        CMP      r4,#3
        BCC      |L1.382|
        POP      {r4,pc}
        ENDP

I2C_Write_ADE7953 PROC
        PUSH     {r4,lr}
        MOVS     r4,#0
        LDR      r0,|L1.1144|
        LDRB     r0,[r0,#0]  ; I2CMasterTxDat
        CMP      r0,#4
        BLE      |L1.416|
        LDR      r0,|L1.1144|
        LDRB     r0,[r0,#0]  ; I2CMasterTxDat
        CMP      r0,#6
        BLE      |L1.424|
|L1.416|
        LDR      r0,|L1.1144|
        LDRB     r0,[r0,#0]  ; I2CMasterTxDat
        CMP      r0,#9
        BLE      |L1.432|
|L1.424|
        ADR      r0,|L1.1068|
        BL       printf
        B        |L1.486|
|L1.432|
        MOVS     r0,#0
        LDR      r1,|L1.1124|
        STR      r0,[r1,#0]  ; ReadFlag
        LDR      r1,|L1.1128|
        STR      r0,[r1,#0]  ; uiMasterTxIndex
        MOV      r0,r1
        LDR      r1,[r0,#0]  ; uiMasterTxIndex
        LDR      r0,[r0,#0]  ; uiMasterTxIndex
        ADDS     r0,r0,#1
        LDR      r2,|L1.1128|
        STR      r0,[r2,#0]  ; uiMasterTxIndex
        LDR      r0,|L1.1144|
        LDRB     r0,[r0,r1]
        LDR      r1,|L1.1132|
        LDR      r1,[r1,#0]  ; pI2CMTX
        STRB     r0,[r1,#0]
        MOVS     r0,#0x70
        BL       I2cMWrCfg
        NOP      
|L1.472|
        LDR      r0,|L1.1136|
        LDRB     r0,[r0,#0]  ; ucComplete
        CMP      r0,#0
        BEQ      |L1.472|
        MOVS     r0,#0
        LDR      r1,|L1.1136|
        STRB     r0,[r1,#0]
|L1.486|
        POP      {r4,pc}
        ENDP

ADE7953_Ex PROC
        PUSH     {r4-r6,lr}
        MOVS     r6,#0
        MOVS     r5,#0
        MOVS     r0,#1
        LDR      r1,|L1.1144|
        STRB     r0,[r1,#0]
        MOVS     r0,#0
        STRB     r0,[r1,#1]
        MOVS     r0,#0x12
        STRB     r0,[r1,#2]
        MOVS     r0,#0x34
        STRB     r0,[r1,#3]
        BL       I2C_Write_ADE7953
        NOP      
        B        |L1.528|
|L1.520|
        ADR      r0,|L1.1140|
        BL       printf
        ADDS     r5,r5,#1
|L1.528|
        CMP      r5,#3
        BLT      |L1.520|
        MOVS     r0,#1
        LDR      r1,|L1.1064|
        STRB     r0,[r1,#0]
        MOVS     r0,#0
        STRB     r0,[r1,#1]
        BL       I2C_Read_ADE7953
        LDR      r0,|L1.1148|
        LDRB     r0,[r0,#1]  ; ucMasterRxDat
        LDR      r1,|L1.1148|
        LDRB     r1,[r1,#0]  ; ucMasterRxDat
        ORR      r4,r0,r1,LSL #8
        MOV      r1,r4
        ADR      r0,|L1.1152|
        BL       printf
        MOV      r0,r6
        POP      {r4-r6,pc}
        ENDP

I2C_MemorySet PROC
        PUSH     {r2-r10,lr}
        MOV      r9,r0
        MOVS     r0,#0
        STR      r0,[sp,#4]
        STR      r0,[sp,#0]
        MOV      r8,#0x20
        MOVS     r5,#0
        MOV      r1,r8
        MOV      r0,r9
        BL       strchr
        MOV      r5,r0
        CBNZ     r5,|L1.604|
|L1.600|
        POP      {r2-r10,pc}
|L1.604|
        LDRB     r0,[r5,#2]
        BL       tolower
        AND      r8,r0,#0xff
        CMP      r8,#0x78
        BNE      |L1.678|
        MOVS     r4,#0
        B        |L1.652|
|L1.624|
        ADDS     r0,r5,#3
        LDRB     r0,[r0,r4]
        CMP      r0,#0x20
        BEQ      |L1.642|
        ADDS     r0,r5,#3
        LDRB     r0,[r0,r4]
        ADD      r1,sp,#4
        STRB     r0,[r1,r4]
        B        |L1.650|
|L1.642|
        MOVS     r0,#0
        ADD      r1,sp,#4
        STRB     r0,[r1,r4]
        B        |L1.656|
|L1.650|
        ADDS     r4,r4,#1
|L1.652|
        CMP      r4,#8
        BLT      |L1.624|
|L1.656|
        NOP      
        ADD      r0,sp,#4
        BL       stoi
        MOV      r7,r0
        ADDS     r0,r5,#3
        ADDS     r1,r0,r4
        ADD      r0,sp,#4
        BL       strcpy
        B        |L1.734|
|L1.678|
        MOVS     r4,#0
        B        |L1.710|
|L1.682|
        ADDS     r0,r5,#1
        LDRB     r0,[r0,r4]
        CMP      r0,#0x20
        BEQ      |L1.700|
        ADDS     r0,r5,#1
        LDRB     r0,[r0,r4]
        ADD      r1,sp,#4
        STRB     r0,[r1,r4]
        B        |L1.708|
|L1.700|
        MOVS     r0,#0
        ADD      r1,sp,#4
        STRB     r0,[r1,r4]
        B        |L1.714|
|L1.708|
        ADDS     r4,r4,#1
|L1.710|
        CMP      r4,#8
        BLT      |L1.682|
|L1.714|
        NOP      
        ADD      r0,sp,#4
        BL       stoi
        MOV      r7,r0
        ADDS     r0,r5,#1
        ADDS     r1,r0,r4
        ADD      r0,sp,#4
        BL       strcpy
|L1.734|
        CMP      r7,#0x4000
        BCC      |L1.772|
        SUB      r0,r7,#0x700
        SUBS     r0,#2
        BEQ      |L1.772|
        CMP      r7,#0x800
        BEQ      |L1.772|
        LDR      r0,|L1.1004|
        ADDS     r0,r0,#0x54
        BL       printf
        MOV      r1,r7
        ADR      r0,|L1.1160|
        BL       printf
        B        |L1.600|
|L1.772|
        MOV      r8,#0x20
        MOV      r1,r8
        ADD      r0,sp,#4
        BL       strchr
        MOV      r5,r0
        LDRB     r0,[r5,#2]
        BL       tolower
        AND      r8,r0,#0xff
        CMP      r8,#0x78
        BNE      |L1.856|
        MOVS     r4,#0
        B        |L1.840|
|L1.806|
        ADDS     r0,r5,#3
        LDRB     r0,[r0,r4]
        CMP      r0,#0x20
        BEQ      |L1.830|
        ADDS     r0,r5,#3
        LDRB     r0,[r0,r4]
        CBZ      r0,|L1.830|
        ADDS     r0,r5,#3
        LDRB     r0,[r0,r4]
        STRB     r0,[sp,r4]
        B        |L1.838|
|L1.830|
        MOVS     r0,#0
        STRB     r0,[sp,r4]
        B        |L1.844|
|L1.838|
        ADDS     r4,r4,#1
|L1.840|
        CMP      r4,#8
        BLT      |L1.806|
|L1.844|
        NOP      
        MOV      r0,sp
        BL       stoi
        MOV      r6,r0
        B        |L1.908|
|L1.856|
        MOVS     r4,#0
        B        |L1.894|
|L1.860|
        ADDS     r0,r5,#1
        LDRB     r0,[r0,r4]
        CMP      r0,#0x20
        BEQ      |L1.884|
        ADDS     r0,r5,#1
        LDRB     r0,[r0,r4]
        CBZ      r0,|L1.884|
        ADDS     r0,r5,#1
        LDRB     r0,[r0,r4]
        STRB     r0,[sp,r4]
        B        |L1.892|
|L1.884|
        MOVS     r0,#0
        STRB     r0,[sp,r4]
        B        |L1.898|
|L1.892|
        ADDS     r4,r4,#1
|L1.894|
        CMP      r4,#8
        BLT      |L1.860|
|L1.898|
        NOP      
        MOV      r0,sp
        BL       atoi
        MOV      r6,r0
|L1.908|
        LSRS     r0,r7,#8
        LDR      r1,|L1.1144|
        STRB     r0,[r1,#0]
        STRB     r7,[r1,#1]
        MOV      r0,r1
        LDRB     r0,[r0,#0]  ; I2CMasterTxDat
        CMP      r0,#9
        BCS      |L1.972|
        TBB      [pc,r0]
        DCB      0x05,0x0a,0x0f,0x16
        DCB      0x16,0x16,0x16,0x06
        DCB      0x07,0x00
        NOP      
        NOP      
        LDR      r1,|L1.1144|
        STRB     r6,[r1,#2]
        B        |L1.990|
        LSRS     r0,r6,#8
        LDR      r1,|L1.1144|
        STRB     r0,[r1,#2]
        STRB     r6,[r1,#3]
        B        |L1.990|
        LSRS     r0,r6,#16
        LDR      r1,|L1.1144|
        STRB     r0,[r1,#2]
        LSRS     r0,r6,#8
        STRB     r0,[r1,#3]
        STRB     r6,[r1,#4]
        B        |L1.990|
|L1.972|
        LSRS     r0,r6,#24
        LDR      r1,|L1.1144|
        STRB     r0,[r1,#2]
        LSRS     r0,r6,#16
        STRB     r0,[r1,#3]
        LSRS     r0,r6,#8
        STRB     r0,[r1,#4]
        STRB     r6,[r1,#4]
        NOP      
|L1.990|
        NOP      
        BL       I2C_Write_ADE7953
        NOP      
        B        |L1.600|
|L1.1000|
        DCD      ||.constdata||
|L1.1004|
        DCD      ||.constdata||+0x150
|L1.1008|
        DCB      "*  1. ADuCM360/361 and ADE7953 I2C Test  *\n",0
|L1.1052|
        DCD      pI2CMRXCNT
|L1.1056|
        DCD      pI2CADR1
|L1.1060|
        DCD      pI2CADR0
|L1.1064|
        DCD      ucMasterRxDevAddr
|L1.1068|
        DCB      "The speicifed ADE7953 register address is out of range\n"
        DCB      0
|L1.1124|
        DCD      ReadFlag
|L1.1128|
        DCD      uiMasterTxIndex
|L1.1132|
        DCD      pI2CMTX
|L1.1136|
        DCD      ucComplete
|L1.1140|
        DCB      " ",0
        DCB      0
        DCB      0
|L1.1144|
        DCD      I2CMasterTxDat
|L1.1148|
        DCD      ucMasterRxDat
|L1.1152|
        DCB      "0x%x \n",0
        DCB      0
|L1.1160|
        DCB      "The address you typed is 0x%x.\n",0
        ENDP

I2C_MemoryGet PROC
        PUSH     {r2-r12,lr}
        MOV      r10,r0
        MOVS     r0,#0
        STR      r0,[sp,#4]
        STR      r0,[sp,#0]
        MOV      r9,#0x20
        MOVS     r5,#0
        MOV      r8,r0
        MOV      r1,r9
        MOV      r0,r10
        BL       strchr
        MOV      r5,r0
        CBNZ     r5,|L1.1228|
|L1.1224|
        POP      {r2-r12,pc}
|L1.1228|
        LDRB     r0,[r5,#2]
        BL       tolower
        AND      r9,r0,#0xff
        CMP      r9,#0x78
        BNE      |L1.1302|
        MOVS     r4,#0
        B        |L1.1276|
|L1.1248|
        ADDS     r0,r5,#3
        LDRB     r0,[r0,r4]
        CMP      r0,#0x20
        BEQ      |L1.1266|
        ADDS     r0,r5,#3
        LDRB     r0,[r0,r4]
        ADD      r1,sp,#4
        STRB     r0,[r1,r4]
        B        |L1.1274|
|L1.1266|
        MOVS     r0,#0
        ADD      r1,sp,#4
        STRB     r0,[r1,r4]
        B        |L1.1280|
|L1.1274|
        ADDS     r4,r4,#1
|L1.1276|
        CMP      r4,#8
        BLT      |L1.1248|
|L1.1280|
        NOP      
        ADD      r0,sp,#4
        BL       stoi
        MOV      r6,r0
        ADDS     r0,r5,#3
        ADDS     r1,r0,r4
        ADD      r0,sp,#4
        BL       strcpy
        B        |L1.1358|
|L1.1302|
        MOVS     r4,#0
        B        |L1.1334|
|L1.1306|
        ADDS     r0,r5,#1
        LDRB     r0,[r0,r4]
        CMP      r0,#0x20
        BEQ      |L1.1324|
        ADDS     r0,r5,#1
        LDRB     r0,[r0,r4]
        ADD      r1,sp,#4
        STRB     r0,[r1,r4]
        B        |L1.1332|
|L1.1324|
        MOVS     r0,#0
        ADD      r1,sp,#4
        STRB     r0,[r1,r4]
        B        |L1.1338|
|L1.1332|
        ADDS     r4,r4,#1
|L1.1334|
        CMP      r4,#8
        BLT      |L1.1306|
|L1.1338|
        NOP      
        ADD      r0,sp,#4
        BL       stoi
        MOV      r6,r0
        ADDS     r0,r5,#1
        ADDS     r1,r0,r4
        ADD      r0,sp,#4
        BL       strcpy
|L1.1358|
        CMP      r6,#0x4000
        BCC      |L1.1396|
        SUB      r0,r6,#0x700
        SUBS     r0,#2
        BEQ      |L1.1396|
        CMP      r6,#0x800
        BEQ      |L1.1396|
        LDR      r0,|L1.2372|
        BL       printf
        MOV      r1,r6
        ADR      r0,|L1.1160|
        BL       printf
        B        |L1.1224|
|L1.1396|
        MOV      r9,#0x20
        MOV      r1,r9
        ADD      r0,sp,#4
        BL       strchr
        MOV      r5,r0
        LDRB     r0,[r5,#2]
        BL       tolower
        AND      r9,r0,#0xff
        CMP      r9,#0x78
        BNE      |L1.1480|
        MOVS     r4,#0
        B        |L1.1464|
|L1.1430|
        ADDS     r0,r5,#3
        LDRB     r0,[r0,r4]
        CMP      r0,#0x20
        BEQ      |L1.1454|
        ADDS     r0,r5,#3
        LDRB     r0,[r0,r4]
        CBZ      r0,|L1.1454|
        ADDS     r0,r5,#3
        LDRB     r0,[r0,r4]
        STRB     r0,[sp,r4]
        B        |L1.1462|
|L1.1454|
        MOVS     r0,#0
        STRB     r0,[sp,r4]
        B        |L1.1468|
|L1.1462|
        ADDS     r4,r4,#1
|L1.1464|
        CMP      r4,#8
        BLT      |L1.1430|
|L1.1468|
        NOP      
        MOV      r0,sp
        BL       stoi
        MOV      r7,r0
        B        |L1.1532|
|L1.1480|
        MOVS     r4,#0
        B        |L1.1518|
|L1.1484|
        ADDS     r0,r5,#1
        LDRB     r0,[r0,r4]
        CMP      r0,#0x20
        BEQ      |L1.1508|
        ADDS     r0,r5,#1
        LDRB     r0,[r0,r4]
        CBZ      r0,|L1.1508|
        ADDS     r0,r5,#1
        LDRB     r0,[r0,r4]
        STRB     r0,[sp,r4]
        B        |L1.1516|
|L1.1508|
        MOVS     r0,#0
        STRB     r0,[sp,r4]
        B        |L1.1522|
|L1.1516|
        ADDS     r4,r4,#1
|L1.1518|
        CMP      r4,#8
        BLT      |L1.1484|
|L1.1522|
        NOP      
        MOV      r0,sp
        BL       atoi
        MOV      r7,r0
|L1.1532|
        MOV      r8,#0
        B        |L1.1702|
|L1.1538|
        LDR      r1,|L1.2376|
        STRB     r6,[r1,#1]
        LSRS     r0,r6,#8
        STRB     r0,[r1,#0]
        BL       I2C_Read_ADE7953
        LDR      r0,|L1.2376|
        LDRB     r0,[r0,#0]  ; ucMasterRxDevAddr
        CMP      r0,#9
        BCS      |L1.1622|
        TBB      [pc,r0]
        DCB      0x05,0x0b
        DCB      0x12,0x1e,0x1e,0x1e
        DCB      0x1e,0x06,0x07,0x00
        NOP      
        NOP      
        LDR      r0,|L1.2380|
        LDRB     r11,[r0,#0]  ; ucMasterRxDat
        B        |L1.1654|
        LDR      r0,|L1.2380|
        LDRB     r0,[r0,#1]  ; ucMasterRxDat
        LDR      r1,|L1.2380|
        LDRB     r1,[r1,#0]  ; ucMasterRxDat
        ORR      r11,r0,r1,LSL #8
        B        |L1.1654|
        LDR      r0,|L1.2380|
        LDRB     r0,[r0,#0]  ; ucMasterRxDat
        LSLS     r0,r0,#16
        LDR      r1,|L1.2380|
        LDRB     r1,[r1,#1]  ; ucMasterRxDat
        ORR      r0,r0,r1,LSL #8
        LDR      r1,|L1.2380|
        LDRB     r1,[r1,#2]  ; ucMasterRxDat
        ORR      r11,r0,r1
        B        |L1.1654|
|L1.1622|
        LDR      r0,|L1.2380|
        LDRB     r0,[r0,#0]  ; ucMasterRxDat
        LSLS     r0,r0,#24
        LDR      r1,|L1.2380|
        LDRB     r1,[r1,#1]  ; ucMasterRxDat
        ORR      r0,r0,r1,LSL #16
        LDR      r1,|L1.2380|
        LDRB     r1,[r1,#2]  ; ucMasterRxDat
        ORR      r0,r0,r1,LSL #8
        LDR      r1,|L1.2380|
        LDRB     r1,[r1,#3]  ; ucMasterRxDat
        ORR      r11,r0,r1
        NOP      
|L1.1654|
        NOP      
        TST      r8,#7
        BNE      |L1.1670|
        MOV      r1,r6
        ADR      r0,|L1.2384|
        BL       printf
|L1.1670|
        AND      r0,r8,#7
        CMP      r0,#7
        BNE      |L1.1688|
        MOV      r1,r11
        ADR      r0,|L1.2392|
        BL       printf
        B        |L1.1696|
|L1.1688|
        MOV      r1,r11
        ADR      r0,|L1.2400|
        BL       printf
|L1.1696|
        ADDS     r6,r6,#1
        ADD      r8,r8,#1
|L1.1702|
        CMP      r8,r7
        BCC      |L1.1538|
        ADR      r0,|L1.2396|
        BL       printf
        NOP      
        B        |L1.1224|
        ENDP

I2C_Test PROC
        PUSH     {r2-r12,lr}
        MOVS     r5,#0
        MOVS     r7,#0
        MOV      r8,r5
        MOV      r10,r5
        LDR      r0,|L1.2408|
        LDR      r0,[r0,#0]  ; pGP2CON
        LDRH     r0,[r0,#0]
        STR      r0,[sp,#4]
        LDR      r0,|L1.2412|
        LDR      r0,[r0,#0]  ; pGP2PUL
        LDRB     r0,[r0,#0]
        STR      r0,[sp,#0]
        MOV      r11,r5
        MOVS     r6,#0
        ADR      r0,|L1.2416|
        BL       printf
        ADR      r0,|L1.2480|
        BL       printf
        LDR      r0,|L1.2524|
        BL       read_reg
        MOV      r6,r0
        ORR      r11,r6,#0x200000
        MOV      r1,r11
        LDR      r0,|L1.2524|
        BL       write_reg
        LDR      r0,|L1.2528|
        LDR      r0,[r0,#0]  ; pCLKDIS
        LDRH     r10,[r0,#0]
        LDR      r0,|L1.2528|
        LDR      r0,[r0,#0]  ; pCLKDIS
        LDRH     r0,[r0,#0]
        MOV      r1,#0x3f3
        ANDS     r0,r0,r1
        LDR      r1,|L1.2528|
        LDR      r1,[r1,#0]  ; pCLKDIS
        STRH     r0,[r1,#0]
        MOV      r0,#0x1312
        LDR      r1,|L1.2532|
        LDR      r1,[r1,#0]  ; pI2CDIV
        STRH     r0,[r1,#0]
        LDR      r0,|L1.2408|
        LDR      r0,[r0,#0]  ; pGP2CON
        LDRH     r0,[r0,#0]
        ORR      r0,r0,#5
        LDR      r1,|L1.2408|
        LDR      r1,[r1,#0]  ; pGP2CON
        STRH     r0,[r1,#0]
        MOVS     r0,#0xfc
        LDR      r1,|L1.2412|
        LDR      r1,[r1,#0]  ; pGP2PUL
        STRB     r0,[r1,#0]
        MOV      r0,#0x131
        LDR      r1,|L1.2536|
        LDR      r1,[r1,#0]  ; pI2CMCON
        STRH     r0,[r1,#0]
        B        |L1.2128|
|L1.1852|
        CMP      r8,#0
        BEQ      |L1.1866|
        CMP      r8,#1
        BNE      |L1.1882|
        B        |L1.1874|
|L1.1866|
        ADR      r0,|L1.2540|
        BL       printf
        B        |L1.1884|
|L1.1874|
        ADR      r0,|L1.2556|
        BL       printf
        B        |L1.1884|
|L1.1882|
        NOP      
|L1.1884|
        NOP      
        LDR      r0,|L1.2576|
        BL       gets
        MOV      r9,r0
        LDR      r0,|L1.2576|
        LDRB     r4,[r0,#0]  ; szTemp
        CMP      r4,#0x6d
        BEQ      |L1.1906|
        CMP      r4,#0x73
        BNE      |L1.1950|
|L1.1906|
        LDR      r0,|L1.2576|
        LDRB     r0,[r0,#1]  ; szTemp
        CMP      r0,#0x41
        BLT      |L1.1930|
        LDR      r0,|L1.2576|
        LDRB     r0,[r0,#1]  ; szTemp
        CMP      r0,#0x5a
        BGT      |L1.1930|
        LDR      r0,|L1.2576|
        LDRB     r0,[r0,#1]  ; szTemp
        ADDS     r0,r0,#0x20
        B        |L1.1944|
|L1.1930|
        LDR      r0,|L1.2576|
        LDRB     r0,[r0,#1]  ; szTemp
        CMP      r0,#0x65
        BEQ      |L1.1942|
        MOVS     r0,#1
        B        |L1.1944|
|L1.1942|
        MOVS     r0,#0
|L1.1944|
        CBZ      r0,|L1.1950|
        MOV      r7,r4
        B        |L1.2038|
|L1.1950|
        CMP      r4,#0xa
        BNE      |L1.1958|
        MOVS     r7,#0x72
        B        |L1.2038|
|L1.1958|
        CMP      r4,#0x41
        BLT      |L1.1972|
        CMP      r4,#0x5a
        BGT      |L1.1972|
        ADD      r0,r4,#0x20
        B        |L1.1982|
|L1.1972|
        CMP      r4,#0x67
        BNE      |L1.1980|
        MOVS     r0,#1
        B        |L1.1982|
|L1.1980|
        MOVS     r0,#0
|L1.1982|
        CBZ      r0,|L1.1994|
        LDR      r0,|L1.2576|
        BL       I2C_MemoryGet
        MOVS     r7,#0x72
        B        |L1.2038|
|L1.1994|
        CMP      r4,#0x41
        BLT      |L1.2008|
        CMP      r4,#0x5a
        BGT      |L1.2008|
        ADD      r0,r4,#0x20
        B        |L1.2018|
|L1.2008|
        CMP      r4,#0x73
        BNE      |L1.2016|
        MOVS     r0,#1
        B        |L1.2018|
|L1.2016|
        MOVS     r0,#0
|L1.2018|
        CBZ      r0,|L1.2030|
        LDR      r0,|L1.2576|
        BL       I2C_MemorySet
        MOVS     r7,#0x72
        B        |L1.2038|
|L1.2030|
        LDR      r0,|L1.2576|
        BL       hextoint
        UXTB     r7,r0
|L1.2038|
        MOVS     r0,#0
        LDR      r1,|L1.2576|
        STRB     r0,[r1,#0]
        CMP      r7,#1
        BEQ      |L1.2058|
        CMP      r7,#0x6d
        BEQ      |L1.2102|
        CMP      r7,#0x73
        BNE      |L1.2114|
        B        |L1.2092|
|L1.2058|
        BL       ADE7953_Ex
        MOV      r5,r0
        ADR      r0,|L1.2580|
        BL       printf
        LDR      r0,|L1.2372|
        ADDS     r0,r0,#0x4c
        BL       printf
        LDR      r0,|L1.2372|
        ADDS     r0,r0,#0x94
        BL       printf
        MOV      r8,#1
        B        |L1.2116|
|L1.2092|
        BL       I2C_menu_display
        MOV      r8,#0
        B        |L1.2116|
|L1.2102|
        BL       menu_display
        MOV      r8,#0
        MOVS     r5,#1
        B        |L1.2116|
|L1.2114|
        NOP      
|L1.2116|
        NOP      
        CMP      r5,#1
        BNE      |L1.2124|
        B        |L1.2130|
|L1.2124|
        AND      r9,r9,r9
|L1.2128|
        B        |L1.1852|
|L1.2130|
        NOP      
        LDR      r0,|L1.2528|
        LDR      r0,[r0,#0]  ; pCLKDIS
        STRH     r10,[r0,#0]
        MOV      r1,#0x200000
        LDR      r0,|L1.2524|
        ADDS     r0,r0,#0x80
        BL       write_reg
        MOV      r1,r6
        LDR      r0,|L1.2524|
        BL       write_reg
        MOV      r0,r5
        POP      {r2-r12,pc}
        ENDP

I2C0_Master_Int_Handler PROC
        PUSH     {r4,lr}
        LDR      r1,|L1.2640|
        LDR      r1,[r1,#0]  ; pI2CMSTA
        LDRH     r0,[r1,#0]
        AND      r1,r0,#8
        CMP      r1,#8
        BNE      |L1.2288|
        LDR      r1,|L1.2644|
        LDR      r1,[r1,#0]  ; pI2CMRX
        LDRB     r2,[r1,#0]
        LDR      r1,|L1.2648|
        LDR      r3,[r1,#0]  ; uiMasterRxIndex
        LDR      r1,[r1,#0]  ; uiMasterRxIndex
        ADDS     r1,r1,#1
        LDR      r4,|L1.2648|
        STR      r1,[r4,#0]  ; uiMasterRxIndex
        LDR      r1,|L1.2380|
        STRB     r2,[r1,r3]
        LDR      r1,|L1.2376|
        LDRB     r1,[r1,#0]  ; ucMasterRxDevAddr
        CMP      r1,#9
        BCS      |L1.2270|
        TBB      [pc,r1]
        DCB      0x05,0x0b,0x13,0x1b
        DCB      0x1b,0x1b,0x1b,0x06
        DCB      0x07,0x00
        NOP      
        NOP      
        MOVS     r1,#0
        LDR      r2,|L1.2648|
        STR      r1,[r2,#0]  ; uiMasterRxIndex
        B        |L1.2286|
        LDR      r1,|L1.2648|
        LDR      r1,[r1,#0]  ; uiMasterRxIndex
        CMP      r1,#1
        BLS      |L1.2252|
        MOVS     r1,#0
        LDR      r2,|L1.2648|
        STR      r1,[r2,#0]  ; uiMasterRxIndex
|L1.2252|
        B        |L1.2286|
        LDR      r1,|L1.2648|
        LDR      r1,[r1,#0]  ; uiMasterRxIndex
        CMP      r1,#2
        BLS      |L1.2268|
        MOVS     r1,#0
        LDR      r2,|L1.2648|
        STR      r1,[r2,#0]  ; uiMasterRxIndex
|L1.2268|
        B        |L1.2286|
|L1.2270|
        LDR      r1,|L1.2648|
        LDR      r1,[r1,#0]  ; uiMasterRxIndex
        CMP      r1,#3
        BLS      |L1.2284|
        MOVS     r1,#0
        LDR      r2,|L1.2648|
        STR      r1,[r2,#0]  ; uiMasterRxIndex
|L1.2284|
        NOP      
|L1.2286|
        NOP      
|L1.2288|
        AND      r1,r0,#4
        CMP      r1,#4
        BNE      |L1.2362|
        LDR      r1,|L1.2652|
        LDR      r1,[r1,#0]  ; ReadFlag
        CMP      r1,#0
        BNE      |L1.2364|
        LDR      r1,|L1.2656|
        LDRB     r1,[r1,#0]  ; I2CMasterTxDat
        CMP      r1,#9
        BCS      |L1.2366|
        TBB      [pc,r1]
        DCB      0x05,0xb6,0xcc,0xe2
        DCB      0xe2,0xe2,0xe2,0x06
        DCB      0x07,0x00
        NOP      
        NOP      
        LDR      r1,|L1.2660|
        LDR      r1,[r1,#0]  ; uiMasterTxIndex
        CMP      r1,#3
        BCS      |L1.2368|
        LDR      r1,|L1.2660|
        LDR      r2,[r1,#0]  ; uiMasterTxIndex
        LDR      r1,[r1,#0]  ; uiMasterTxIndex
        ADDS     r1,r1,#1
        LDR      r3,|L1.2660|
        STR      r1,[r3,#0]  ; uiMasterTxIndex
        LDR      r1,|L1.2656|
        LDRB     r1,[r1,r2]
        LDR      r2,|L1.2664|
        LDR      r2,[r2,#0]  ; pI2CMTX
        STRB     r1,[r2,#0]
        B        |L1.2678|
|L1.2362|
        B        |L1.2856|
|L1.2364|
        B        |L1.2814|
|L1.2366|
        B        |L1.2768|
|L1.2368|
        B        |L1.2668|
        DCW      0x0000
|L1.2372|
        DCD      ||.constdata||+0x1a4
|L1.2376|
        DCD      ucMasterRxDevAddr
|L1.2380|
        DCD      ucMasterRxDat
|L1.2384|
        DCB      "0x%x   ",0
|L1.2392|
        DCB      "0x%x"
|L1.2396|
        DCB      "\n",0
        DCB      0
        DCB      0
|L1.2400|
        DCB      "0x%x ",0
        DCB      0
        DCB      0
|L1.2408|
        DCD      pGP2CON
|L1.2412|
        DCD      pGP2PUL
|L1.2416|
        DCB      "\n====================================================="
        DCB      "=====\n",0
        DCB      0
        DCB      0
        DCB      0
|L1.2480|
        DCB      "This Session is about I2C of ADuCM360/361\n",0
        DCB      0
|L1.2524|
        DCD      0xe000e100
|L1.2528|
        DCD      pCLKDIS
|L1.2532|
        DCD      pI2CDIV
|L1.2536|
        DCD      pI2CMCON
|L1.2540|
        DCB      "LoveJongSu/I2C]",0
|L1.2556|
        DCB      "LoveJongSu/ADE7953]",0
|L1.2576|
        DCD      szTemp
|L1.2580|
        DCB      "*  1. I2C test on ADE7953 Slave and ADuCM360/361 Master"
        DCB      " *\n",0
        DCB      0
|L1.2640|
        DCD      pI2CMSTA
|L1.2644|
        DCD      pI2CMRX
|L1.2648|
        DCD      uiMasterRxIndex
|L1.2652|
        DCD      ReadFlag
|L1.2656|
        DCD      I2CMasterTxDat
|L1.2660|
        DCD      uiMasterTxIndex
|L1.2664|
        DCD      pI2CMTX
|L1.2668|
        MOV      r1,#0x111
        LDR      r2,|L1.2960|
        LDR      r2,[r2,#0]  ; pI2CMCON
        STRH     r1,[r2,#0]
|L1.2678|
        B        |L1.2812|
        LDR      r1,|L1.2964|
        LDR      r1,[r1,#0]  ; uiMasterTxIndex
        CMP      r1,#4
        BCS      |L1.2712|
        LDR      r1,|L1.2964|
        LDR      r2,[r1,#0]  ; uiMasterTxIndex
        LDR      r1,[r1,#0]  ; uiMasterTxIndex
        ADDS     r1,r1,#1
        LDR      r3,|L1.2964|
        STR      r1,[r3,#0]  ; uiMasterTxIndex
        LDR      r1,|L1.2968|
        LDRB     r1,[r1,r2]
        LDR      r2,|L1.2972|
        LDR      r2,[r2,#0]  ; pI2CMTX
        STRB     r1,[r2,#0]
        B        |L1.2722|
|L1.2712|
        MOV      r1,#0x111
        LDR      r2,|L1.2960|
        LDR      r2,[r2,#0]  ; pI2CMCON
        STRH     r1,[r2,#0]
|L1.2722|
        B        |L1.2812|
        LDR      r1,|L1.2964|
        LDR      r1,[r1,#0]  ; uiMasterTxIndex
        CMP      r1,#5
        BCS      |L1.2756|
        LDR      r1,|L1.2964|
        LDR      r2,[r1,#0]  ; uiMasterTxIndex
        LDR      r1,[r1,#0]  ; uiMasterTxIndex
        ADDS     r1,r1,#1
        LDR      r3,|L1.2964|
        STR      r1,[r3,#0]  ; uiMasterTxIndex
        LDR      r1,|L1.2968|
        LDRB     r1,[r1,r2]
        LDR      r2,|L1.2972|
        LDR      r2,[r2,#0]  ; pI2CMTX
        STRB     r1,[r2,#0]
        B        |L1.2766|
|L1.2756|
        MOV      r1,#0x111
        LDR      r2,|L1.2960|
        LDR      r2,[r2,#0]  ; pI2CMCON
        STRH     r1,[r2,#0]
|L1.2766|
        B        |L1.2812|
|L1.2768|
        LDR      r1,|L1.2964|
        LDR      r1,[r1,#0]  ; uiMasterTxIndex
        CMP      r1,#6
        BCS      |L1.2800|
        LDR      r1,|L1.2964|
        LDR      r2,[r1,#0]  ; uiMasterTxIndex
        LDR      r1,[r1,#0]  ; uiMasterTxIndex
        ADDS     r1,r1,#1
        LDR      r3,|L1.2964|
        STR      r1,[r3,#0]  ; uiMasterTxIndex
        LDR      r1,|L1.2968|
        LDRB     r1,[r1,r2]
        LDR      r2,|L1.2972|
        LDR      r2,[r2,#0]  ; pI2CMTX
        STRB     r1,[r2,#0]
        B        |L1.2810|
|L1.2800|
        MOV      r1,#0x111
        LDR      r2,|L1.2960|
        LDR      r2,[r2,#0]  ; pI2CMCON
        STRH     r1,[r2,#0]
|L1.2810|
        NOP      
|L1.2812|
        B        |L1.2856|
|L1.2814|
        LDR      r1,|L1.2964|
        LDR      r1,[r1,#0]  ; uiMasterTxIndex
        CMP      r1,#2
        BCS      |L1.2846|
        LDR      r1,|L1.2964|
        LDR      r2,[r1,#0]  ; uiMasterTxIndex
        LDR      r1,[r1,#0]  ; uiMasterTxIndex
        ADDS     r1,r1,#1
        LDR      r3,|L1.2964|
        STR      r1,[r3,#0]  ; uiMasterTxIndex
        LDR      r1,|L1.2976|
        LDRB     r1,[r1,r2]
        LDR      r2,|L1.2972|
        LDR      r2,[r2,#0]  ; pI2CMTX
        STRB     r1,[r2,#0]
        B        |L1.2856|
|L1.2846|
        MOV      r1,#0x111
        LDR      r2,|L1.2960|
        LDR      r2,[r2,#0]  ; pI2CMCON
        STRH     r1,[r2,#0]
|L1.2856|
        AND      r1,r0,#0x100
        CMP      r1,#0x100
        BNE      |L1.2882|
        MOV      r1,#0x131
        LDR      r2,|L1.2960|
        LDR      r2,[r2,#0]  ; pI2CMCON
        STRH     r1,[r2,#0]
        MOVS     r1,#1
        LDR      r2,|L1.2980|
        STRB     r1,[r2,#0]
|L1.2882|
        NOP      
        NOP      
        NOP      
        DSB      
        NOP      
        NOP      
        POP      {r4,pc}
        ENDP

UART_ISR PROC
        PUSH     {r3,lr}
        MOVS     r0,#0
        STR      r0,[sp,#0]
        LDR      r0,|L1.2984|
        LDR      r0,[r0,#0]  ; pCOMIIR
        LDRB     r0,[r0,#0]
        STR      r0,[sp,#0]
        LDRB     r0,[sp,#0]
        AND      r0,r0,#7
        CMP      r0,#2
        BNE      |L1.2930|
        MOVS     r0,#1
        LDR      r1,|L1.2988|
        STRB     r0,[r1,#0]
|L1.2930|
        LDRB     r0,[sp,#0]
        AND      r0,r0,#7
        CMP      r0,#4
        BNE      |L1.2958|
        LDR      r0,|L1.2992|
        LDR      r0,[r0,#0]  ; pCOMTX_RX
        LDRB     r0,[r0,#0]
        LDR      r1,|L1.2996|
        STRB     r0,[r1,#0]
        MOVS     r0,#1
        LDR      r1,|L1.3000|
        STRB     r0,[r1,#0]
|L1.2958|
        POP      {r3,pc}
        ENDP

|L1.2960|
        DCD      pI2CMCON
|L1.2964|
        DCD      uiMasterTxIndex
|L1.2968|
        DCD      I2CMasterTxDat
|L1.2972|
        DCD      pI2CMTX
|L1.2976|
        DCD      ucMasterRxDevAddr
|L1.2980|
        DCD      ucComplete
|L1.2984|
        DCD      pCOMIIR
|L1.2988|
        DCD      ucTxBufferEmpty
|L1.2992|
        DCD      pCOMTX_RX
|L1.2996|
        DCD      GetStrTmp
|L1.3000|
        DCD      ucWaitForUart

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.bss||, DATA, NOINIT, ALIGN=0

szTemp
        %        80

        AREA ||.constdata||, DATA, READONLY, ALIGN=2

        DCB      0x2a,0x2a,0x2a,0x2a
        DCB      0x2a,0x2a,0x2a,0x2a
        DCB      0x2a,0x2a,0x2a,0x2a
        DCB      0x2a,0x2a,0x2a,0x2a
        DCB      0x2a,0x2a,0x2a,0x2a
        DCB      0x2a,0x2a,0x2a,0x2a
        DCB      0x2a,0x2a,0x2a,0x2a
        DCB      0x2a,0x2a,0x2a,0x2a
        DCB      0x2a,0x2a,0x2a,0x2a
        DCB      0x2a,0x2a,0x2a,0x2a
        DCB      0x2a,0x2a,0x2a,0x2a
        DCB      0x2a,0x2a,0x2a,0x2a
        DCB      0x2a,0x2a,0x2a,0x2a
        DCB      0x2a,0x2a,0x2a,0x2a
        DCB      0x2a,0x2a,0x2a,0x2a
        DCB      0x2a,0x2a,0x2a,0x2a
        DCB      0x2a,0x2a,0x2a,0x2a
        DCB      0x2a,0x2a,0x2a,0x2a
        DCB      0x2a,0x2a,0x2a,0x2a
        DCB      0x2a,0x2a,0x2a,0x2a
        DCB      0x2a,0x2a,0x0a,0x00
        DCB      0x2a,0x2a,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x0a,0x00,0x00
        DCB      0x2a,0x2a,0x20,0x20
        DCB      0x20,0x4e,0x6f,0x74
        DCB      0x65,0x20,0x3a,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x0a,0x00,0x00
        DCB      0x2a,0x2a,0x20,0x20
        DCB      0x20,0x41,0x44,0x75
        DCB      0x43,0x4d,0x33,0x36
        DCB      0x30,0x2f,0x33,0x36
        DCB      0x31,0x20,0x4d,0x61
        DCB      0x73,0x74,0x65,0x72
        DCB      0x20,0x61,0x6e,0x64
        DCB      0x20,0x4f,0x74,0x68
        DCB      0x65,0x72,0x20,0x53
        DCB      0x6c,0x61,0x76,0x65
        DCB      0x20,0x44,0x65,0x76
        DCB      0x69,0x63,0x65,0x73
        DCB      0x20,0x49,0x32,0x43
        DCB      0x20,0x54,0x65,0x73
        DCB      0x74,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x0a,0x00,0x00
        DCB      0x2a,0x2a,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x32,0x30,0x31
        DCB      0x34,0x2c,0x20,0x31
        DCB      0x30,0x2c,0x20,0x32
        DCB      0x32,0x20,0x20,0x42
        DCB      0x79,0x20,0x4c,0x69
        DCB      0x6d,0x20,0x4a,0x6f
        DCB      0x6e,0x67,0x20,0x53
        DCB      0x75,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x20,0x20
        DCB      0x20,0x20,0x0a,0x00
        DCB      0x54,0x68,0x65,0x20
        DCB      0x73,0x70,0x65,0x63
        DCB      0x69,0x66,0x69,0x65
        DCB      0x64,0x20,0x61,0x64
        DCB      0x64,0x72,0x65,0x73
        DCB      0x73,0x20,0x69,0x73
        DCB      0x20,0x6f,0x75,0x74
        DCB      0x20,0x6f,0x66,0x20
        DCB      0x72,0x61,0x6e,0x67
        DCB      0x65,0x20,0x69,0x6e
        DCB      0x20,0x41,0x44,0x45
        DCB      0x37,0x39,0x35,0x33
        DCB      0x20,0x69,0x6e,0x74
        DCB      0x65,0x72,0x6e,0x61
        DCB      0x6c,0x20,0x72,0x65
        DCB      0x67,0x69,0x73,0x74
        DCB      0x65,0x72,0x20,0x73
        DCB      0x65,0x74,0x21,0x21
        DCB      0x21,0x0a,0x00,0x00
        DCB      0x2a,0x20,0x20,0x20
        DCB      0x2d,0x3e,0x20,0x57
        DCB      0x72,0x69,0x74,0x65
        DCB      0x20,0x30,0x78,0x31
        DCB      0x32,0x33,0x34,0x20
        DCB      0x31,0x36,0x2d,0x62
        DCB      0x69,0x74,0x20,0x64
        DCB      0x61,0x74,0x61,0x20
        DCB      0x69,0x6e,0x74,0x6f
        DCB      0x20,0x30,0x78,0x31
        DCB      0x30,0x30,0x20,0x41
        DCB      0x44,0x45,0x37,0x39
        DCB      0x35,0x33,0x20,0x69
        DCB      0x6e,0x74,0x65,0x72
        DCB      0x6e,0x61,0x6c,0x20
        DCB      0x72,0x65,0x67,0x69
        DCB      0x73,0x74,0x65,0x72
        DCB      0x20,0x2a,0x0a,0x00
        DCB      0x2a,0x20,0x20,0x20
        DCB      0x2d,0x3e,0x20,0x41
        DCB      0x66,0x74,0x65,0x72
        DCB      0x20,0x72,0x65,0x61
        DCB      0x64,0x69,0x6e,0x67
        DCB      0x20,0x30,0x78,0x31
        DCB      0x30,0x30,0x20,0x41
        DCB      0x44,0x45,0x37,0x39
        DCB      0x35,0x33,0x20,0x69
        DCB      0x6e,0x74,0x65,0x72
        DCB      0x6e,0x61,0x6c,0x20
        DCB      0x72,0x65,0x67,0x69
        DCB      0x73,0x74,0x65,0x72
        DCB      0x2c,0x20,0x73,0x68
        DCB      0x6f,0x77,0x2e,0x2e
        DCB      0x2e,0x20,0x2a,0x0a
        DCB      0x00

        AREA ||.data||, DATA, ALIGN=2

Pulse
        DCB      0x00
GonStop
        DCB      0x00
PowerFlag
        DCB      0x00,0x00
ReadFlag
        DCD      0x00000000
uiMasterRxIndex
        DCD      0x00000000
uiMasterTxIndex
        DCD      0x00000000
I2CMasterTxDat
        DCB      0x01,0x00,0x12,0x34
        DCB      0x56,0x78
ucMasterRxDevAddr
        DCB      0x01,0x00
ucMasterRxDat
        DCB      0x00,0x00,0x00,0x00
ucComplete
        DCB      0x00

        EXPORT I2C_menu_display [CODE]
        EXPORT I2cMRdCfg [CODE]
        EXPORT I2cMWrCfg [CODE]
        EXPORT I2C_Read_ADE7953 [CODE]
        EXPORT I2C_Write_ADE7953 [CODE]
        EXPORT ADE7953_Ex [CODE]
        EXPORT I2C_MemorySet [CODE]
        EXPORT I2C_MemoryGet [CODE]
        EXPORT I2C_Test [CODE]
        EXPORT I2C0_Master_Int_Handler [CODE]
        EXPORT UART_ISR [CODE]
        EXPORT szTemp [DATA,SIZE=80]
        EXPORT Pulse [DATA,SIZE=1]
        EXPORT GonStop [DATA,SIZE=1]
        EXPORT PowerFlag [DATA,SIZE=1]
        EXPORT ReadFlag [DATA,SIZE=4]
        EXPORT uiMasterRxIndex [DATA,SIZE=4]
        EXPORT uiMasterTxIndex [DATA,SIZE=4]
        EXPORT I2CMasterTxDat [DATA,SIZE=6]
        EXPORT ucMasterRxDevAddr [DATA,SIZE=2]
        EXPORT ucMasterRxDat [DATA,SIZE=4]
        EXPORT ucComplete [DATA,SIZE=1]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT printf [CODE]
        IMPORT pI2CMRXCNT [DATA]
        IMPORT pI2CADR1 [DATA]
        IMPORT pI2CADR0 [DATA]
        IMPORT pI2CMTX [DATA]
        IMPORT strchr [CODE]
        IMPORT tolower [CODE]
        IMPORT stoi [CODE]
        IMPORT strcpy [CODE]
        IMPORT atoi [CODE]
        IMPORT read_reg [CODE]
        IMPORT write_reg [CODE]
        IMPORT gets [CODE]
        IMPORT hextoint [CODE]
        IMPORT menu_display [CODE]
        IMPORT pGP2CON [DATA]
        IMPORT pGP2PUL [DATA]
        IMPORT pCLKDIS [DATA]
        IMPORT pI2CDIV [DATA]
        IMPORT pI2CMCON [DATA]
        IMPORT pI2CMSTA [DATA]
        IMPORT pI2CMRX [DATA]
        IMPORT pCOMIIR [DATA]
        IMPORT ucTxBufferEmpty [DATA]
        IMPORT pCOMTX_RX [DATA]
        IMPORT GetStrTmp [DATA]
        IMPORT ucWaitForUart [DATA]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
